### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by DyfeStrax** [tristanmelton/TimeTraveler#4]
Hope you can fix this bug! I really would like to play this mod, it looks so cool!!!

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2/17/14 12:10 AM
Description: Initializing game

java.lang.VerifyError: Instruction type does not match stack map
Exception Details:
  Location:
    timeTraveler/network/TimeTravelerPacketHandler.onPacketData(Lnet/minecraft/nbt/NBTBase;Lnet/minecraft/network/packet/Packet103SetSlot;Lcpw/mods/fml/common/network/Player;)V @87: iload
  Reason:
    Type 'net/minecraft/world/gen/ChunkProviderServer' (current frame, locals[7]) is not assignable to 'net/minecraft/world/ColorizerGrass' (stack map, locals[7])
  Current Frame:
    bci: @87
    flags: { }
    locals: { 'timeTraveler/network/TimeTravelerPacketHandler', 'net/minecraft/nbt/NBTBase', 'net/minecraft/network/packet/Packet103SetSlot', 'cpw/mods/fml/common/network/Player', 'java/io/DataInputStream', 'timeTraveler/mechanics/FutureTravelMechanics', integer, 'net/minecraft/world/gen/ChunkProviderServer', integer }
    stack: { }
  Stackmap Frame:
    bci: @87
    flags: { }
    locals: { 'timeTraveler/network/TimeTravelerPacketHandler', 'net/minecraft/nbt/NBTBase', 'net/minecraft/network/packet/Packet103SetSlot', 'cpw/mods/fml/common/network/Player', 'java/io/DataInputStream', 'timeTraveler/mechanics/FutureTravelMechanics', integer, 'net/minecraft/world/ColorizerGrass', integer }
    stack: { }
  Bytecode:
    0000000: 2cb4 0019 121b b600 2199 0008 2a2c b600
    0000010: 252c b400 1912 27b6 0021 9900 6bbb 0029
    0000020: 59bb 002b 592c b400 2fb7 0032 b700 353a
    0000030: 04bb 0037 59b7 0038 3a05 1904 b600 3c36
    0000040: 0603 b800 423a 07b2 0048 1506 b600 4e19
    0000050: 07c6 002a 0336 0815 0815 06a2 0020 b200
    0000060: 4815 06b6 004e 1905 1907 b600 5819 0519
    0000070: 0705 b600 5c84 0801 a7ff dfa7 000a 3a05
    0000080: 1905 b600 5f2c b400 1912 61b6 0021 9900
    0000090: b903 b800 423a 04bb 0029 59bb 002b 592c
    00000a0: b400 2fb7 0032 b700 353a 0519 05b6 0065
    00000b0: 3a06 1905 b600 3c36 0719 05b6 003c 3608
    00000c0: 1905 b600 3c36 0919 05b6 0065 b800 6b3a
    00000d0: 0a19 0619 04b8 0070 3a0b 190b c600 2e19
    00000e0: 0b15 0787 b500 7619 0b15 0887 b500 7919
    00000f0: 0b15 0987 b500 7cb2 0048 190b b600 7f19
    0000100: 0419 0bb6 0083 57a7 0036 bb00 8559 1904
    0000110: b700 873a 0c19 0c15 0787 b500 8a19 0c15
    0000120: 0887 b500 8d19 0c15 0987 b500 90b2 0048
    0000130: 190c b600 7f19 0419 0cb6 0083 57a7 000a
    0000140: 3a06 1906 b600 912c b400 1912 93b6 0021
    0000150: 9900 4d03 b800 423a 04bb 0029 59bb 002b
    0000160: 592c b400 2fb7 0032 b700 353a 0519 05b6
    0000170: 0065 3a06 1905 b600 3c36 0719 05b6 003c
    0000180: 3608 1905 b600 3c36 0919 05b6 0065 b800
    0000190: 6b3a 0aa7 000a 3a06 1906 b600 91b1  
  Exception Handler Table:
    bci [49, 123] => handler: 126
    bci [171, 317] => handler: 320
    bci [365, 403] => handler: 406
  Stackmap Table:
    same_frame(@17)
    full_frame(@87,{Object[#2],Object[#80],Object[#21],Object[#82],Object[#41],Object[#55],Integer,Object[#84],Integer},{})
    full_frame(@123,{Object[#2],Object[#80],Object[#21],Object[#82],Object[#41]},{})
    same_locals_1_stack_item_frame(@126,Object[#17])
    chop_frame(@133,1)
    full_frame(@266,{Object[#2],Object[#80],Object[#21],Object[#82],Object[#84],Object[#41],Object[#29],Integer,Integer,Integer,Object[#103],Object[#114]},{})
    full_frame(@317,{Object[#2],Object[#80],Object[#21],Object[#82],Object[#84],Object[#41]},{})
    same_locals_1_stack_item_frame(@320,Object[#19])
    chop_frame(@327,2)
    full_frame(@406,{Object[#2],Object[#80],Object[#21],Object[#82],Object[#84],Object[#41]},{Object[#19]})
    chop_frame(@413,2)

```
at java.lang.Class.getDeclaredConstructors0(Native Method)
at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
at java.lang.Class.getConstructor0(Unknown Source)
at java.lang.Class.newInstance(Unknown Source)
at cpw.mods.fml.common.network.NetworkModHandler.tryCreatingPacketHandler(NetworkModHandler.java:195)
at cpw.mods.fml.common.network.NetworkModHandler.configureNetworkMod(NetworkModHandler.java:143)
at cpw.mods.fml.common.network.NetworkModHandler.<init>(NetworkModHandler.java:102)
at cpw.mods.fml.common.network.FMLNetworkHandler.registerNetworkMod(FMLNetworkHandler.java:263)
at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:519)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
at com.google.common.eventbus.EventBus.post(EventBus.java:267)
at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
at com.google.common.eventbus.EventBus.post(EventBus.java:267)
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
at cpw.mods.fml.common.Loader.loadMods(Loader.java:511)
at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:183)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:473)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
at net.minecraft.client.main.Main.main(SourceFile:101)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
```
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
    at java.lang.Class.getConstructor0(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at cpw.mods.fml.common.network.NetworkModHandler.tryCreatingPacketHandler(NetworkModHandler.java:195)
    at cpw.mods.fml.common.network.NetworkModHandler.configureNetworkMod(NetworkModHandler.java:143)
    at cpw.mods.fml.common.network.NetworkModHandler.<init>(NetworkModHandler.java:102)
    at cpw.mods.fml.common.network.FMLNetworkHandler.registerNetworkMod(FMLNetworkHandler.java:263)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:519)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:511)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:183)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:473)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 508955544 bytes (485 MB) / 724566016 bytes (691 MB) up to 2863661056 bytes (2731 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 4 mods loaded, 4 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed
    FML{6.4.49.965} [Forge Mod Loader](minecraftforge-9.11.1.965.jar) Unloaded->Constructed
    Forge{9.11.1.965} [Minecraft Forge](minecraftforge-9.11.1.965.jar) Unloaded->Constructed
    charsmud_timetraveler{0.1} [Time Traveler](TimeTravelerPreRelease.zip) Unloaded
    Launched Version: 1.6.4-Forge9.11.1.965
    LWJGL: 2.9.0
    OpenGL: GeForce GTX 670MX/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Pack: Default
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

**Comment by ilovespacesprojects** [comment]
im using 1.6.2 and i still get a fucking crash
